### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-12: ordinal not in range(128)

### ISSUE THREAD

**Issue by nikit0zzz** [itkach/mwscrape#10]
hello , help to solve the problem
(env-mwscrape)root@nikitozzz:~# mwscrape http://sportwiki.to/ --site-path=/
Starting session sportwiki-to-1439500632-631
Starting at None
0 5-HTP
5-HTP is up to date (rev. 60706), skipping
Traceback (most recent call last):
  File "/root/env-mwscrape/bin/mwscrape", line 9, in <module>
    load_entry_point('mwscrape==1.0', 'console_scripts', 'mwscrape')()
  File "/root/env-mwscrape/local/lib/python2.7/site-packages/mwscrape/scrape.py", line 489, in main
    for page in ipages(pages):
  File "/root/env-mwscrape/local/lib/python2.7/site-packages/mwscrape/scrape.py", line 472, in ipages
    print('%7s %s' % (index, title))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-12: ordinal not in range(128)

**Comment by itkach** [comment]
looks like this was resolved at some point ¯\_(ツ)_/¯
